edition = "2021"
style_edition = "2024"
max_width = 120
fn_call_width = 120

unstable_features = true

group_imports = "StdExternalCrate"
imports_granularity = "Module"
format_code_in_doc_comments = true
doc_comment_code_block_width = 120
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
