edition = "2021"
max_width = 120

unstable_features = true

group_imports = "StdExternalCrate"
version = "Two"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true

