[package]
name = "wwwtech_rs"
version = "1.1.5"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.1.0"
tokio = "1.19.2"
actix-files = "0.6.1"
actix-service = "2.0.2"
futures = "0.3"
env_logger = "0.9"
actix-http = "3.1.0"
actix-identity = "0.5.0"
actix-session = { version = "0.7.0", features = ["cookie-session"] }
serde = "1.0"
serde_json = "1.0"
diesel = { version = "^1.4", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "1.4.0"
dotenv = "0.15"
chrono = {version = "0.4", features = ["serde"] }
timeago = "0.3"
pulldown-cmark = { version = "0.9", default-features = false, features = ["simd"] }
askama = "0.11"
argonautica = "0.2"
atom_syndication = "0.11"
validator = { version = "0.15", features = ["derive"] }
anyhow = "1.0"
actix-web-httpauth = "0.6.0"

# pictures
actix-multipart = "0.4.0"
futures-util = "0.3"
tempfile = "3"
new_mime_guess = "4.0"
image = "0.24"
base64 = "0.13"
kamadak-exif = "0.5"

# webmentions
url = "2.2"
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
visdom = "0.5"
itertools = "0.10"
urlencoding = "2.1"
lettre = "0.10.0"

# error reporting
sentry = "0.27"
sentry-actix = "0.27"


[build-dependencies]
askama = "0.11"
