[package]
name = "wwwtech_rs"
version = "1.0.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5"
# actix 3 uses actix-service 1.0
actix-service = "1.0"
futures = "0.3"
env_logger = "0.9"
actix-http = "2"
# actix-utils = "3"
actix-identity = "0.3"
serde = "1.0"
serde_json = "1.0"
diesel = { version = "^1.4", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15"
chrono = {version = "0.4", features = ["serde"] }
timeago = "0.3"
pulldown-cmark = { version = "0.9", default-features = false, features = ["simd"] }
askama = { git = "https://github.com/djc/askama.git" }
argonautica = "0.2"
atom_syndication = "0.11"
validator = { version = "0.14", features = ["derive"] }
# can't use background-jobs 0.11, yet
background-jobs = "0.8"
anyhow = "1.0"
actix-web-httpauth = "0.5"

# pictures
actix-multipart = "0.3"
futures-util = "0.3"
tempfile = "3"
new_mime_guess = "4.0"
image = "0.23"
base64 = "0.13"

# webmentions
url = "2.2"
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
visdom = "0.4"
itertools = "0.10"
urlencoding = "2.1"


[build-dependencies]
askama = { git = "https://github.com/djc/askama.git" }
