[package]
name = "wwwtech_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5"
env_logger = "0.9"
tera = "1.8"
actix-http = "2"
# actix-utils = "3"
serde = "1.0"
serde_json = "1.0"
diesel = { version = "^1.4", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15"
chrono = {version = "0.4", features = ["serde"] }