[package]
name = "wwwtech_rs"
version = "1.1.16"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.2.1"
tokio = "1.21.2"
actix-files = "0.6.2"
actix-service = "2.0.2"
futures = "0.3"
env_logger = "0.9"
actix-http = "3.2.2"
actix-identity = "0.5.2"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
serde = "1.0"
serde_json = "1.0"
diesel = { version = "^2.0", features = ["postgres", "r2d2", "chrono"] }
diesel_migrations = "2.0.0"
dotenv = "0.15"
chrono = { version = "0.4", default-features = false, features = ["std", "serde"] }
pulldown-cmark = { version = "0.9", default-features = false, features = ["simd"] }
askama = "0.11"
atom_syndication = "0.11"
validator = { version = "0.16", features = ["derive"] }
anyhow = "1.0"
actix-web-httpauth = "0.8.0"

argon2 = "0.4"

# pictures
actix-multipart = "0.4.0"
futures-util = "0.3"
tempfile = "3"
new_mime_guess = "4.0"
image = "0.24"
base64 = "0.13"
kamadak-exif = "0.5"

# webmentions
url = "2.3"
regex = "1"
reqwest = { version = "0.11", features = ["blocking"] }
visdom = "0.5"
itertools = "0.10"
urlencoding = "2.1"
lettre = "0.10.1"

# error reporting
sentry = "0.27"
sentry-actix = "0.28"


[build-dependencies]
askama = "0.11"
