[package]
name = "wwwtech_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.5"
env_logger = "0.9"
actix-http = "2"
# actix-utils = "3"
actix-identity = "0.3"
serde = "1.0"
serde_json = "1.0"
diesel = { version = "^1.4", features = ["postgres", "r2d2", "chrono"] }
dotenv = "0.15"
chrono = {version = "0.4", features = ["serde"] }
timeago = "0.3"
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }
askama = { git = "https://github.com/djc/askama.git" }
argonautica = "0.2"
atom_syndication = "0.11"
validator = { version = "0.12", features = ["derive"] }

[build-dependencies]
askama = { git = "https://github.com/djc/askama.git" }
