ALTER TABLE articles
  ALTER COLUMN content_warning TYPE CHARACTER VARYING(255);
ALTER TABLE notes
  ALTER COLUMN content_warning TYPE CHARACTER VARYING(255);
ALTER TABLE pictures
  ALTER COLUMN content_warning TYPE CHARACTER VARYING(255);
ALTER TABLE deafies
  ALTER COLUMN content_warning TYPE CHARACTER VARYING(255);
