#!/usr/bin/env bash

set -e

latest_version=$(git tag | sort -rV |  head -1)
HOST=$1
VERSION=$2
DIR=/home/ckruse/www/wwwtech

HOST="${HOST:=web.defunced.de}"
VERSION="${VERSION:=$latest_version}"

if [[ ! -f  .build/releases/wwwtech-$VERSION.tar.gz ]]; then
    echo "release $VERSION could not be found!"
    exit 1
fi

scp .build/releases/wwwtech-$VERSION.tar.gz $HOST:$DIR
ssh $HOST "cd $DIR && tar -xf wwwtech-$VERSION.tar.gz && cp -r wwwtech-$VERSION/* . || exit 0"

ssh root@$HOST "systemctl restart wwwtech"

echo "waiting 5 seconds for the release to start up"
sleep 5

ssh $HOST "cd $DIR && ./bin/wwwtech rpc 'Wwwtech.Release.migrate'"
ssh $HOST "cd $DIR && rm -rf wwwtech-$VERSION.tar.gz wwwtech-$VERSION/"

